


INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (8, 27, 1, 86, 'When Larry and I were little, grandma had a tradition of inviting us individually for a special overnight visit where we got to decide what to play/eat/do the whole time.  I remember one visit where we first went to the store to pick out a cereal for the morning (anything I wanted- chose Lucky Charms), had some ice cream at the newton corner Baskin Robbins, listened to old music and played with a new Barbie in the kitchen sink all night  :)', 'Diane', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (9, 62, 1, 86, 'Grandma was much more tough + fearless than the rest of us.  I remember one time when I was 9 or so, dad was away I think and we had a mouse in the basement that was freaking out me and mom.  Grandma came over to the rescue after the traps had a catch- but instead of just disposing of the mice + traps at once, she EMPTIED the traps by hand so we could reuse them', 'Diane', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (10, 62, 1, 86, 'I always remember grandma shopping and gardening- if she found a good deal on something she would stock up (an understatement), and would swing by the house with some for us too.  She would also come around gardening sometimes, and at one point she had a gardening plot where I think she grew vegetables.  She would also go berry picking in the summer locally and sometimes she took us too :)', 'Diane', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (11, 61, 1, 72, 'Mom and Catherine were really close when they were younger. Catherine worked atBell laboratories and got mom a job there one summer. They lived together for awhile when their husbands were in WWII. She really enjoyed their phone callsover the past year and she took Aunt Catherines passing to heart.', 'Anita', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (12, 62, 1, 72, 'Mom and Catherine were really close when they were younger. Catherine worked at Bell laboratories and got mom a job there one summer. They lived together for awhile when their husbands were in WWII. She really enjoyed their phone callsover the past year and she took Aunt Catherines passing to heart.', 'Anita', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (13, 146, 1, 72, 'I had Izzy for health class in highschool. When she came over to the house shed have a beer with dad and made meswear never to tell anyone at school that she drank. She was this tiny littleold lady and was the most of the most respected and feared teachers.', 'Anita', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (14, 237, 1, NULL, '[Nicholas Keem] said his father Martin Keem Sr. while blasting in the Erie Canal had the misfortune of fracturing a leg, whereupon he came to Sheldon for asylum and care.  This would indicate kinfolk.  Furthermore, the incident happened before 1826, when the canal was in operation.', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (15, 62, 1, 72, 'I always thought Uncle Bob and Aunt Catherine were such a good looking couple.  They were both a lot of fun and livened things up when we were all together.', 'Anita', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (16, 75, 1, 72, 'I always thought Uncle Bob and Aunt Catherine were such a good looking couple.  They were both a lot of fun and livened things up when we were all together.', 'Anita', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (17, 23, 1, NULL, 'The family moved up to Burlington when Stanley was in high school.  Bessie & Louis moved back down to MA when Norman was a senior in med school, so Norman and Stanley lived together for a couple years, renting rooms with a professor.  One year Stanley had the lead in the high school play, and Norman practiced with him, training him on expressions.', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (18, 15, 1, 24, 'She would make a penny go a mile.  [paraphrased: She was very clean, and swept the steps and the sidewalk.  She was strong in the household.]', 'Norman', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (19, 24, 1, NULL, 'In high school, Norman was the president of the \"Quarter Club\"- they had 25 members and it cost 25 cents to come and play pool.  When Norman moved up to Burlington, he was given the pool table, and they kept it in the attic.', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (20, 25, 2, NULL, 'In Burlington, Norman worked in Matthews/Louis shoe store on Friday afternoons.  Annette was the cashier at the store.  Every Friday night theyd go dancing at a local roller rink that would bring in an outside band.  On Sunday theyd go horseback riding.  Also Norman got a \"fold boat\" and he bought a lanteen sail and a keel for it- theyd go out together on Lake Champlain.', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (21, 24, 1, NULL, 'Norman was a medical officer for a platoon.  The family lived together in Texas for 2 years.  Beth was born during this time, and they rented a home rather than living in barracks.  Norman was scheduled to go over to Japan, but the war ended before it was time.', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (22, 30, 1, 24, 'Larry was very kind- he was good to the whole family.', 'Norman', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (23, 30, 1, NULL, '<a href="/people/5">Jack</a> and Larry were in the same fraternity together.', NULL, NULL, true, '2005-08-29', now());

INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (24, 5, 1, NULL, 'Jack and <a href="/people/30">Larry</a> were in the same fraternity together.', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (25, 174, 1, 24, 'Leonard was very social, and worked at a bakery.  He made our wedding cake.', 'Norman', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (26, 17, 1, NULL, 'According to Norman, Solomon was short and Ida was tall', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (27, 16, 1, NULL, 'According to Norman, Solomon was short and Ida was tall', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (28, 4, 2, NULL, 'Norman went to stay with Solomon & Ida for a little while when Bessie was pregnant with Stanley', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (29, 19, 1, NULL, 'According to Norman, Charlie was handsome and married someone wealthy.', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (30, 15, 1, 86, 'Bubbie had long long hair that shed wear up in a bun.  Whenever wed go to visit, shed have a dish of peanuts and raisins on the table.  Wed all sit and talk, and I remember her as warm and digified.  The combination of peanuts and raisins still makes me think of those visits.', 'Diane', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (31, 29, 1, 31, 'When Kalman Kobrin landed in New York, USA, he couldnt speak English.  The immigration officials somehow tagged Kalman with the surname of Kaplan.  Consequently, subsequent generations carry the surnname Kaplan instead of Kobrin.  The surname was maintained even upon Kalman becoming a United States citizen', 'Joe Kaplan', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (32, 92, 1, 31, 'My son Kalman Kobrin had the surname legall changed back to Kobrin on October 25, 1957, at the Probate Court in the County of Middlesex, in the Commonwealth of Massachusetts (document No. 345411)', 'Joe Kaplan', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (33, 90, 2, NULL, 'The Kobrins family trade in Russia was harness-making.  Kalman had 2 brothers and 1 sister who left Russia and settled in South Africa during the same time that he left for the USA.  At the time of his brothers arrival in South Africa, the Great Boar War had broken out.  Because of this, the Kobrin brothers received some large contracts with the South African Army to make riding breeches for their calvary forces.  Due to these large contracts they became very wealthy and acquired a very large estate which was later passed on to their children in South Africa.', NULL, NULL, true, '2005-08-29', now());

INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (34, 32, 1, NULL, 'Medical info: she was only around 5 tall- juvenile diabetic on insulin.  overweight in later years.', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (35, 379, 1, NULL, 'Mary wrote this note in <a href="/people/62">Kays</a> childhood autograph book on April 30, 1931: Dear Catherine,  Once I went into a garden to pick a mess of peas And I nearly died laughing to see a chicken sneeze  Your cousin Mary Suttell', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (36, 374, 1, NULL, 'Edna wrote this note in <a href="/people/62">Kays</a> childhood autograph book on August 30, 1931 (on a page thats now greenish blue): Dear Catherine,  Never feel as the color of this page With Love Edna', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (37, 60, 1, NULL, 'Doris wrote this note in <a href="/people/62">Kays</a> childhood autograph book on April 10,1932: Dear Sister, Loyal friendship pure and true.  Such as that I feel for you. Your Sister, Doris M Keem', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (38, 61, 1, NULL, 'Viola wrote this note in <a href="/people/62">Kays</a> childhood autograph book on November 1, 1933: Dear Sister, The night was dark and dreary, the billy goat was blindHe backed into a barbed wire fenceand scratched his nevermindYour Sister, Viola Keem', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (39, 73, 1, 181, 'She was a lovely lady', 'Tess', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (40, 169, 1, 420, 'Sam Nitkin learned the leather trade in Russia, and emigrated to the US. With the automobile becoming dominant and the horse industry fading, he turned to building trades. He was a painter for commercial properties. He lived in the South End of Boston until 1935, at which time he moved with his family to the Dorchester/Mattapan section of Boston. Sam Nitkin was active in organized labor, and was a president of the labor union local that represented painters in Boston. He never owned a house, but his apartment in his later years - in the Georgtown development in Hyde Park - was a regular gathering place for his family. His children and grandchildren would gather on weekends, either for French toast in the morning or Kentucky Fried Chicken at night. He loved to talk politics with his family and play the card game pinochle. He taught his grandchildren how to play poker, and gave them little gifts like flashlights. He made a point of buying a tallis and tfilon for each of his grandsons when they were Bar Mitzvahed.', 'David Nitkin', NULL, true, '2005-08-29', now());

INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (41, 14, 1, 420, 'She was a quiet woman, but strong.', 'David Nitkin', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (42, 318, 1, 96, 'Married to Richard Swartz 8-27-1996, lives in North Andover, MA.  Has 2 step sons Jonathan & Daniel Swartz            ', 'Rosealyn Nolan', '2010-02-04 13:29:34', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (43, 96, 1, 96, ' Married David Clark Nolan 11-29-2008.           ', 'Rosealyn Nolan', '2010-02-04 13:37:55', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (45, 75, 1, 81, '          Born in Buffalo, incredible athlete--minor league baseball, golf.  Local involvement: planning board, volunteer fire department  ', 'Susan Kaplan', '2010-03-11 11:19:33', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (47, 146, 1, 81, '          Izzy was very close to Kay. The two of them were disapproved of by their mother in law (Sarah) and established a loving bond together. Izzy loved Debbie, Robby and Susan alot and treated them like the children she couldnt have.   ', 'Susan Kaplan', '2010-03-11 11:24:26', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (48, 43, 1, 81, 'She was a tiny woman and an incredibly hard worker. She lived with Leona for many years in a home with a coal stove and in those times, no electricity in the upstairs. When we would stay there, we took candles upstairs to go to bed--very exciting for us as kids.             ', 'Susan Kaplan', '2010-03-11 11:29:09', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (49, 73, 1, 81, 'She was always well dressed and quite stylish. She doted on her grandchildren and her sons.             ', 'Susan Kaplan', '2010-03-11 11:31:53', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (50, 58, 1, 81, 'It was said that Leona was born at home and did not receive enough oxygen at birth. She was devoted to her mother and lived with her for many years, caring for the house and her mothers needs. She loved the visits from us kids and was interested in anything we were doing. She had a Christmas cookie collection from year to year,  saving the best cookie from the previous year--she really did it to amuse us.             ', 'Susan Kaplan', '2010-03-11 11:36:25', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (51, 66, 1, 81, 'Patty, Maria, Cathy and I were all cousins of the same age, all had fun when we were together. Patty was warm, generous and giving in every way. I wish that we could find a way to contact her.            ', 'Susan Kaplan', '2010-03-11 11:38:19', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (52, 59, 1, 81, 'Kay was always grateful to Helen and felt that she was incredibly generous with her as the kid sister in terms of school and life in general. Helen was extremely religious. When we would stay there, each night we would say the rosary, kneeling on the floor in the living room.             ', 'Susan Kaplan', '2010-03-11 11:42:48', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (53, 61, 1, 81, 'Kay adored Viola and had a wonderful relationship with her. She felt that Viola was sweet as a sister and valued their relationship in later life as well.             ', 'Susan Kaplan', '2010-03-11 11:47:05', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (54, 43, 1, 79, 'We visited Grandma once a year - a long drive from Albany - I only remember her from about age 86 and up.  She was teenee-tiny and she and Leona were \"green\" way before their time.  They saved and reused things that other people didnt in those times, but now we would be so proud of their recycling ways.  Their house was so homey and I always wished to play the piano.  I often did play the pump organ in the garage (no one could hear my beginner attempts at playing).  My favorite memory was the maple cookies (pure maple sugar hardened into a cookie) they would dole out when we came.            ', 'Deborah Bartlett', '2010-03-14 15:44:45', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (55, 60, 1, 79, 'I remember staying with Aunt Doris & Uncle Jerome when we would come to visit.  The farm house always had fresh milk from the cows with cream floating on top.  Once when we were there I helped Aunt Doris can fruits and jams for the winter and my most vibrant memory was my mom & dad playing Pinochle and Euchre til all hours of the morning.            ', 'Deborah Bartlett', '2010-03-14 15:55:09', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (56, 63, 1, 79, 'I remember Uncle Jerome as a quiet kind of hard working man - always seemed very kind to us as kids.            ', 'Deborah Bartlett', '2010-03-14 15:56:05', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (57, 59, 1, 79, 'I remember Mom (Kay) talking about how Helen was her grade school teacher when she was growing up and how hard that was.  \"Imagine coming home and my teacher would be right there telling me I didnt study for a test enough\"!  Mom felt she couldnt get away with any slacking - in her heart I know she felt it was great that Helen was always there to push her to do her best.              ', 'Deborah Bartlett', '2010-03-14 15:59:34', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (58, 61, 1, 79, 'I remember mom telling me that she and Aunt Viola lived away from home one summer and were nannies for some family in Buffalo.  It allowed them to go to school in the city and they earned their way by taking care of this familys kids and house.  Their father certainly taught all of his daughters how to earn their own way.  It is still something I admire of this whole family of women.            ', 'Deborah Bartlett', '2010-03-14 16:02:05', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (59, 81, 1, 79, 'This is my fabulous sister whom I love & admire so much.  I adored her as a child and still do as an adult.  I love you Susie!  ', 'Deborah Bartlett', '2010-03-14 16:06:52', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (60, 80, 1, 79, 'This is my brother who means so much to me.  He took care of me many times when I was a kid, always stumbling or hurting myself.  He now has a wonderful family who I adore and know he is happy in his life.            ', 'Deborah Bartlett', '2010-03-14 16:10:30', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (61, 85, 1, 79, 'I have so many memories of Larry, as a baby, boy and now as an adult.  Larry is the kindest person I know, always there with a laugh and love for those around him.            ', 'Deborah Bartlett', '2010-03-14 16:11:58', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (62, 86, 1, 79, 'Diane is my favorite (and only) girl in our family.  We are blessed to have her in our family.  She brings a strong womans point of view to our lives. She is adventurous and loves life.            ', 'Deborah Bartlett', '2010-03-14 16:13:56', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (63, 602, 1, 597, 'Son Dennis lives in Florida .. Pensacola            ', 'Myrna Pochel', '2010-03-14 23:16:08', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (64, 591, 1, 597, 'Son Ray deceased owns business 3 blocks from me-Pochels Appliances            ', 'Myrna Pochel', '2010-03-14 23:17:49', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (1, 48, 2, 82, 'We lived in Hyde Park, an urban neighborhood of Boston.  Our main family vacations were camping in Maine.  My brother John was an alter boy.  My sister Kathy bowled candlepin.  I played hockey on the field down the street.  My frather owned and operated a service station, where John and I worked when we reached 16.  Both JOhn and Kathy went to Hyde Park HS, and I went to Catholic Memorial HS because of the unrest in Boston Schools due to forced bussing.  My mother Barbara stayed at home and raised the kids and did the banking for my fathers business.', 'Paul', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at, for_self) VALUES (3, 79, 1, 79, 'My primary interest is of course, my family.  Paul + I are very involved with our kids, Dan + Joe. When they were little I got involved in their elementary school- JFK Memorial.  I became the PCC Chairman + was in office for 3 years.  I was then on the School Improvement Council and finally ran for public office in 2003 and was elected to the Franklin Town Council.  This work keeps me very busy. </p>The rest of my waking moments are spent going to the kids activities- hockey, soccer, bands + jazz bands.  I live a very full life with Paul and I dont think we will ever say we wasted time in our lives or were bored!</p>', NULL, NULL, true, '2005-08-29', now(), true);
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (4, 79, 1, 86, 'At Christmas time, Debbie is the cookie <b>master</b>!  She has containers and containers of every imaginable kind- old favorites and always some new recipes too', 'Diane', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (5, 82, 1, NULL, 'Most of my time is spent coaching the kids sports teams, both hockey and soccer.  I started as an assistant coach when Danny started playing travel hockey in 1998.  Now Im mostly involved with Joeys soccer teams.  Ouside of the kids sports Im involved with town volunteer stuff.  I spent two years on the school districts NetDay Committee wiring all the schools for Internet access.  In 1999 I ran for Town Council and lost by 33 votes.  I served for 6 years on the towns Finanace Committee.  With all our volunteer work Deb and I have very little down time, but we find it very rewarding.</p>', NULL, NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (6, 16, 2, 79, 'We live in Franklin, MA.  We enjoy our home where we live with Pikachu, our Golden Retriever.  We enjoy the kids sports and music.  Our family traditions are: <ul><li>Saratoga NY Jazz Festival with Ben, Denise, Janet, + Al.  </li><li>Summer vacation at Bartons Motel, Lake Winnepesaukee. </li><li>Apple picking at Tougas Farm in Northborough, MA. </li><li>Christmas Eve at Susies, and Christmas morning with crepes (supplied by Larry + Diane) and strawberries + blueberries and fresh whipped cream here at our house. </li></ul>', 'Debbie', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (7, 15, 2, 79, 'We grew up in Voorheesville, NY.  I remember always having pets, both cats and dogs.  I also remember Dad hunting with them + bringing home his catch.  Mom and I would prep the bird for cooking and discuss basic biology. </p>I remember Mom always keeping the house neat + clean and being a good cook.  She was very strong with me as her daughter, telling me that I needed an education + needed to be able to support myself. I spent a lot of time with her in the kitchen listening to her stories or cooking information, sitting at the little kitchen table.  </p>One of the traditions was the Punkin Town Fair- benefitted the volunteer New Salem Fire Department.  Dad was the chairman for a few years and mom did cotton candy and I had free reign of the place.  Voorheesville was a fun place to grow up- safe, but sometimes boring. </p>', 'Debbie', NULL, true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (65, 591, 1, 597, 'Also a daughter who works for NASA and you will find her all over the internet.  I think the name is Carol.            ', 'Myrna Pochel', '2010-03-14 23:19:18', true, '2005-08-29', now());


INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (66, 606, 1, 597, 'The name may be Ernest..deceased.            ', 'Myrna Pochel', '2010-03-14 23:20:55', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (67, 601, 1, 597, 'Daughter Patti Potter lives in Gold Hill, Oregon.  We maintain contact.  She is on Facebook and has 2 daughters.            ', 'Myrna Pochel', '2010-03-14 23:22:19', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (68, 605, 1, 597, 'Arley Pochel Kohler lives in Seattle. She has a daughter in Seattle.  Son Ralph passed away.            ', 'Myrna Pochel', '2010-03-14 23:24:11', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (69, 601, 1, 597, 'Sarah deceased in 1987            ', 'Myrna Pochel', '2010-03-14 23:26:48', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (70, 595, 1, 597, 'Children: Peter Strumski, Jeff Strumski,Ralph Strumski(deceased),Diane Greer Miller, Joyce Greer, Ron Greer Miller            ', 'Myrna Pochel', '2010-03-14 23:36:44', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (71, 596, 1, 597, '            ', 'Myrna Pochel', '2010-03-14 23:39:22', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (72, 597, 1, 597, 'Born: July 31, 1937 in South Bend, WA3 sons, Guy Vance, Mark Vance, Eric Vance all living in Tacoma, WA            ', 'Myrna Pochel', '2010-03-14 23:41:26', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (73, 597, 1, 597, 'Retired from Pierce County Library System as a computer technician in 2001.            ', 'Myrna Pochel', '2010-03-14 23:42:49', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (74, 79, 1, 81, 'Debs--you are the best sister anyone could have...I love you more than you know. You are an incredible mother a warm, funny, unbelievably generous person.             ', 'Susan Kaplan', '2010-03-19 13:37:42', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (75, 84, 1, 81, 'Joey as a little boy was so passionate about every thing that interested him--he was (and is!) a joy and treasure to all of us.            ', 'Susan Kaplan', '2010-03-19 13:48:15', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (76, 83, 1, 81, 'Dan has always been a wonderful part of our family as well as Deb and Pauls from the night of his birth on. He is a strong, independent young man really beginning a new part of his life at Northeastern. ', 'Susan Kaplan', '2010-03-19 13:52:23', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (79, 125, 1, 125, 'Dad, Mom, Alicia and I celebrating Cousin Kennys 70th birthday with extended family.  Cousins, uncles, etc.  GREAT weekend in Mass.            ', 'Debbie Feinberg', '2010-03-25 23:43:49', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (80, 25, 1, 125, 'Matthew loved children and loved Ann, his wife dearly.  He ate bran cereal for breakfast, a tuna sandwich and fruit for lunch and fish, salad and rice for dinner.  He ate basically the same food daily at approximately the same time.        ', 'Deborah Kallman', '2010-03-26 00:20:32', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (82, 113, 1, 125, 'Anns home was spotless. She always welcomed us with a warm smile, bagels, cream cheese and fresh orange juice. Beds always had fresh, ironed linens and everything smelled like clean spring air.            ', 'Deborah Kallman', '2010-03-27 18:45:50', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (83, 198, 1, 81, 'My father would take me to visit Aunt Al and Aunt Joe. Aunt Al was, at that time, in her 90s and was rather stern and serious.            ', 'Susan Kaplan', '2010-03-30 10:55:58', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (84, 197, 1, 81, 'My father would take me to visit Aunt Al and Aunt Jo whenever we were in Buffalo. Aunt Jo was the livlier of the two and would have special treats for me and joked around about family members.            ', 'Susan Kaplan', '2010-03-31 10:07:15', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (85, 43, 1, 80, 'It was always an adventure going to grandmas house.  The earliest memories I have is of her old farmhouse (the house she had before the state decided to claim it for a road I think).  Anyhow there wasw a big living room/parlor with a big pot-bellied coal stove at one end  and us little kids would be on stools  at the opposite end..the end  the heat never reached.  Anyhow the water came from collected rainwater and the greatest adventure of all..grandma had an outhouse.  Imagine my poor fathers face when I shook him awake at 3:00am to take me to the outhouse in the dead of winter..hey thats what dads are for. Grandma was indeed a tiny little  woman..but a farm girl through and through.  I remember one time  she was getting ready to make chicken dinner for all of us..only the chicken was coming from a  small coop she had.  She sliced the head  off neatly and then proceeded to laugh with us children as the headless chicken ran in circles for a good couple  of minutes.            ', 'Robert Husband', '2010-04-14 16:17:17', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (86, 43, 1, 80, 'Whenever we came to visit grandma she always had some  old newspaper clipping that she thought would interest you (in my case because I was tall for my age shed drag out a story about a 9 foot tall african guy..another time it was about a prehistoric fish fossil).  The tough part about visting grandma was always  saying the  rosary just before bedtime..utter torture for a little  kid as it just went on and on.  Whenever it was getting time  to go Grandma would  disappear for a bit then come back and make you feel real guilty..\"oh dear, Im feeling really old  today, Ill make it through spring, but that will  be  it you  wont see me again.\"  Then everyone  would  gather round  and make a big fuss and  wed have to stay for another couple  of hours until wed be getting ready to go and the act would begin all over  again.  She and  Aunt Leona used to make these sugar cookies for us..trouble is  theys bake them around Christmas and hold  on to them until we  arrived some  time in  August...hard as hockey pucks but whatever  she had in them ... no mold ever got on those cookies.            ', 'Robert Husband', '2010-04-14 16:25:58', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (87, 76, 1, 80, 'Memories of Uncle Rich: We didn’t get to see Uncle Rich a whole lot.  He would be on a road trip (I believe he used to work for Dell comic books when we were all little) in the general area and drop in for a day or two with a boat load of ‘little lulu’, ‘Ritchie Rich’  or ‘Archie and Jughead’ comics  He wasn’t a particularly tall man but always trim and in good shape.  He loved to laugh and tease us little kids in a good natured way.  He always called me ‘tiger’ and would immediately go to grab me by the hair on entering the house, but as I always had a brush cut in those days he would only grab air.  Then he’d grab my head in a headlock and punish my lack of hair by giving me semi-painful nuggies until I yelled ‘uncle….RICH’.  Seemed to be a happy-go-lucky kind of guy, quick with a joke and laughed a lot. I remember Mom telling me that Rich was a boxer both in the army and after the war as a semi-pro in and around Buffalo.  Very quick hands, stiff jab and a real dancer in the ring.  Problem was that although he didn’t take a lot of punishment when he did get hit flush on the jaw…down he would go like a sack of potatoes…glass jaw.  His career as a boxer, was therefore short-lived.            ', 'Robert Husband', '2010-04-30 16:41:30', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (88, 91, 1, 188, 'she loved to cook and when she did it was for an army. I do not recall her ever cooking for less than that. ', 'Barry Kloper', '2010-06-19 11:54:55', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (89, 92, 1, 188, 'Uncle Kal was like a surrogate father to us (my brother, sister, and me) after our father had died. ', 'Barry Kloper', '2010-06-19 11:55:13', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (90, 87, 1, 89, 'Kal was a WWII veteran who received a heros welcome home, along with the distinguished flying cross.His love for tennis allowed him to keep playing until the age of 80! He played a strong mental as well as physical game. On the court he was the drop shot king! Everyone knew him for his patience and kindness. ', 'Andrea OBrien', '2010-06-25 14:29:10', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (92, 80, 1, 81, 'Rob is the most wonderful father and not a bad brother either! He gave the absolute most accurate and humerous and moving story of our mothers life at her funeral...I will never forget it.            ', 'Susan Kaplan', '2010-06-29 13:23:28', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (93, 82, 1, 81, '          Paul is a wonderful member of our family--a great Dad and husband and alot of fun to be with and talk to.   ', 'Susan Kaplan', '2010-06-29 13:26:09', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (94, 43, 1, 86, 'From Mary Ann Metzger: I knew Adell, she was so upset when they took her house down for the new road. Think she just sat in it. My Grandpa Schiltz sold her a lot in town and they built a small home, still kept very nice by new owners. ', 'Diane Kaplan', '2010-10-25 17:33:03', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (95, 17, 1, 114, 'We  lived in Brookline  and my parents would occasionally invite him for dinner. He was a sweet man. I also remember that he always brought something, probably candy. My Mother was touched by that, given his age and fraility.', 'Eleanor Feinberg', '2010-11-20 16:30:17', true, '2005-08-29', now());
INSERT INTO Notes (id, ref_id, type, author, body, author_name, date, active, created_at, updated_at) VALUES (96, 17, 1, 36, '<a href="/people/15">Bubbie</a> called him Schveh (yiddish for father in law), he would come over sometimes for dinner.  He was a quiet man, nice enough- hed sit quietly in a chair and read his paper (The Jewish Advocate).  It was a different time then.  Once when I was 4 or 5 years old I was playing with a boot, walking it around the floor. I walked it around and over him, and he gave a look of surprise: not unfriendly or particularly angry, but a look that I should know I shouldnt be doing that. There was a degree of formality that we dont have today, and children were to be seen and not heard.', 'Ken Kaplan', '2010-11-20 16:38:10', true, '2005-08-29', now());


