
INSERT INTO stories (id, description, image, intro, slug, source, created_at, updated_at) VALUES (797, 'Glaser family and the civil war', NULL, 'At that time the country was torn by the Civil War (1861-1865) in which nearly half a million American soldiers lost their lives, more than in the second World War! The three youngest, American-born sons had followed Lincolns call to volunteer…', 'glasersCivilwar', 'Sheila Glaser Bultmanns paper', '2005-08-29', now());
INSERT INTO stories (id, description, image, intro, slug, source, created_at, updated_at) VALUES (798, 'Frank Glasers Strykersville Brewery', 'M1-83_Strykersville_Brewery.jpg', 'The most disastrous fire this village has ever known occurred on Fri. afternoon, Aug 13, 1909. The large brewery with Hotel attached, owned by Frank Glaser…', 'frankGlaserBrewery', 'Compiled by Mary Ann Metzger', '2005-08-29', now());
INSERT INTO stories (id, description, image, intro, slug, source, created_at, updated_at) VALUES (799, 'Peter Reisdorfs Mill', 'MReisdorf_mill.jpg', 'The Reisdorfs operated a saw mill, grist mill, cider mill and the cooper shop, where he made barrels. The waterfall on the creek provided power to operate the mill and several hired men and later family members labored in the mills and farm operation…', 'PeterReisdorfMill', 'Compiled by Mary Ann Metzger', '2005-08-29', now());
INSERT INTO stories (id, description, image, intro, slug, source, created_at, updated_at) VALUES (800, 'John Keems Obituary', NULL, 'John Keem, a well known and nearly life long resident of Wales, died at his home in that town on Wednesday, January 30, after a lingering illness at the age of 84 years…', 'JohnKeemObit', NULL, '2005-08-29', now());
INSERT INTO stories (id, description, image, intro, slug, source, created_at, updated_at) VALUES (801, 'Mary Reisdorfs Obituary', NULL, 'We are pained to announce the death of Mrs. Mary Glaser, wife of Peter Reisdorf, which occurred at her late home in Strykersville, N.Y., April 20th 1890, at the age of 59 years 11 months, 13 days, of stomach difficulty…', 'MaryReisdorfObit', NULL, '2005-08-29', now());


INSERT INTO stories (id, description, image, intro, slug, source, created_at, updated_at) VALUES (802, 'Emily Tusks Obituary', NULL, 'Mrs. Emily Tusk, one of Sheldons most remarkable women passed away at the home of her son Albert Smith at Wales Center Sunday afternoon at 2 o clock, March 3rd after a weeks illness of influenza followed by pneumonia...', 'EmilyTuskObit', NULL, '2005-08-29', now());
INSERT INTO stories (id, description, image, intro, slug, source, created_at, updated_at) VALUES (803, 'Frank Glasers Civil War Soldier Record', NULL, 'Name: Frank GleaserEnlistment Date: 11 August 1862  Distinguished Service: DISTINGUISHED SERVICE …', 'FrankGlaserSoldier', 'Mary Ann Metzger', '2005-08-29', now());
