


INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (1, 'Diane Kaplan', 'dianekaplan@gmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2015-01-04 18:47:15', 86, '2005-08-29', '2010-10-25 00:00:00', true, true, true, true, 417, true, '', true, '<a href="/families/218">The Zöhlers (Mathias & Maria)</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (3, 'Susan Kaplan', 'kaplanfin@aol.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2011-08-16 13:59:13', 81, '2005-08-29', '2010-10-25 00:00:00', true, true, true, true, 16, true, '', true, '<a href="/families/218">The Zöhlers (Mathias & Maria)</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (2, 'Larry Kaplan', 'lkaplan000@gmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2014-05-10 17:08:18', 85, '2005-08-29', '2010-10-25 00:00:00', true, true, true, true, 10, true, '', true, '<a href="/families/218">The Zöhlers (Mathias & Maria)</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (4, 'Ken Kaplan', 'kenkaplan@aol.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2013-08-30 21:56:03', 36, '2005-08-29', '2010-11-13 00:00:00', false, false, true, true, 14, true, NULL, false, '<a href="/families/3">Ida & Barnett Kaplan</a>, <a href="/families/4">Solomon & Ida Kemler</a>,<a href="/families/90">Aaron & Rochel Kobrin</a>,<a href="/families/119">Max & Toba Shapiro</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (7, 'Elaine Dolph', 'ekdolph@comcast.net', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-07-08 22:35:06', 37, '2005-08-29', '2010-11-13 00:00:00', false, false, true, true, 2, true, NULL, false, '<a href="/families/3">Ida & Barnett Kaplan</a>, <a href="/families/4">Sol & Ida Kemler</a>,<a href="/families/90">Aaron & Rochel Kobrin</a>,<a href="/families/119">Max & Toba Shapiro</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (6, 'Bob Husband', 'rwhusband@yahoo.com', false, '$2y$10$ObxobpzBAFF35EGKSQiR.ubv9Ib9nNTv9IL3IfNQAY7jSm0PEflsa', '2014-05-08 14:43:43', 80, '2005-08-29','2010-10-25 00:00:00', true, true, false, false, 13, true, '', false, '<a href="/families/218">The Zöhlers (Mathias & Maria)</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (5, 'Deb Bartlett', 'bartlett.family@comcast.net', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-07-05 20:05:51', 79, '2005-08-29', '2010-10-25 00:00:00', true, true, false, false, 5, true, '', false, '<a href="/families/218">The Zöhlers (Mathias & Maria)</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (9, 'Laurie Dolph', 'ladolph@comcast.net', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', NULL, 40, '2005-08-29', NULL, false, false, true, true, 0, true, NULL, false, '<a href="/families/3">Ida & Barnett Kaplan</a>, <a href="/families/4">Sol & Ida Kemler</a>, <a href="/families/90">Aaron & Rochel Kobrin</a>, <a href="/families/119">Max & Toba Shapiro</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (32, 'Andy Dolph', 'acdolph@comcast.net', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', NULL, 39, '2005-08-29', NULL, false, false, true, true, NULL, true, NULL, false, '<a href="/families/3">Ida & Barnett Kaplan</a>, <a href="/families/4">Sol & Ida Kemler</a>, <a href="/families/90">Aaron & Rochel Kobrin</a>, <a href="/families/119">Max & Toba Shapiro</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (18, 'David Nitkin', 'dbnitkin66@hotmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-03-20 08:52:44', 420, '2005-08-29', '2010-09-14 00:00:00', false, false, true, false, 1, true, 'See ''Kaplan side''; Ida & Barnett were the parents of your paternal grandmother Etta Nitkin.', false, 'Father''s Mother''s side: great grandparents <a href="/families/3">Ida & Barnett Kaplan</a><br/>Father''s father''s side: great grandparents <a href="/families/123">Nathaniel & Lena Nitkin Kaplan</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access, husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (26, 'Anita Gorruso', 'anita_gorruso@yahoo.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2015-12-22', 72, '2005-08-29', '2015-12-22 00:00:00', true, false, false, false, 1, true, 'This is the history of your mom''s side (Kay Husband was Viola''s sister)', false, '<a href="/families/218">The Zöhlers (Mathias & Maria)</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (49, 'Judi Kloper', 'judiko@aol.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', NULL, 189, '2010-06-19 00:00:00', '2015-12-23', false, false, false, true, 0, true, 'This is the history of your maternal great grandparents (via Mildred Kloper and Joe Kaplan).', false, 'Great great great grandparents (mothers mothers side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (50, 'Wendy Kloper', 'hon600rr@yahoo.com', false, '$2y$10$Dh0xIcBiUybZ5qiRvp/MsutxGFdTyQaiCQm3mJGKtVdbnwqgqZdMy', '2015-12-24 09:30:28', 572, '2010-06-20 00:00:00', '2010-08-21 00:00:00', false, false, false, true, 2, true, 'This is the history of your paternal great great grandparents (via Barry Kloper, Mildred Kloper, Joe Kaplan). ', false, 'Great great great great grandparents (fathers mothers side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (51, 'Andrea O''Brien','andreaobrien1@hotmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2011-03-23 20:30:20', 89, '2010-06-23 00:00:00', '2010-07-06 00:00:00', false, false, false, true, 8, true, 'This is the history of your paternal great grandparents (via Kal Alman and Sarah Alman).', false, 'Great great great grandparents (fathers mothers side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (22, 'Barry Kloper', 'PRECHER@aol.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2014-02-09 18:14:57', 188, '2005-08-29', '2010-08-21 00:00:00', false, false, false, true, 5, true, 'This is the history of your maternal great grandparents (via Mildred Kloper and Joe Kaplan). ', false, 'Great great great grandparents (mother''s mother''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (20, 'Joe Kobrin', 'joseph@kobrin.co.uk', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', NULL, 464, '2005-08-29', '2010-07-06 00:00:00', false, false, false, true, NULL, true, 'This is the history of your paternal great great grandparents (via Dave Kobrin, Joe Kobrin, Solomon Kobrin & Rebecca).', false, 'Great great great grandparents (father''s father''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access, husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (34, 'Rose Schultz-Nolan', 'RNolan410@gmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-02-04 13:27:00', 96, '2010-01-24 00:00:00', '2010-08-20 00:00:00', false, false, false, true, 2, true, 'This is the history of your paternal great great grandparents (via Jeff Schultz, Dorothy Schultz, and Joe Kaplan).', false, 'Great great great great grandparents (father''s mother''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (10, 'Andrea Kemler', 'akemler@comcast.net', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-06-27 18:10:21', 108, '2005-08-29', '2010-06-27 00:00:00', false, false, true, false, 1, true, 'This is the history of your dad''s side (Norman Kemler was Gert''s sister)', false, 'Father''s side: 2 sets of great grandparents:<br/><a href="/families/3">Ida & Barnett Kaplan</a><br/><a href="/families/4">Solomon & Ida Kemler</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (12, 'Beth Kemler', 'bethkemler@aol.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-07-13 21:52:22', 106, '2005-08-29', '2010-11-13 00:00:00', false, false, true, false, 2, true, 'This is the history of your dad''s side (Norman Kemler was Gert''s sister)', false, 'Father''s side: 2 sets of great grandparents:<br/><a href="/families/3">Ida & Barnett Kaplan</a><br/><a href="/families/4">Solomon & Ida Kemler</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (8, 'Dan Bartlett', 'drbartlett24@gmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-10-26 09:17:07', 83, '2005-08-29', '2010-10-25 00:00:00', true, true, false, false, 1, true, '', false, '<a href="/families/218">The Zöhlers (Mathias & Maria)</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (104, 'Joe Bartlett', 'jbartlet@umass.edu', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-10-26 09:17:07', 84, now(), now(), true, true, false, false, NULL, true, '', false, '<a href="/families/218">The Zöhlers (Mathias & Maria)</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (48, 'Stacey Rutherford', 'kittyfelone@gmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2011-01-01 20:32:04', 573, '2010-06-19 00:00:00', '2010-08-21 00:00:00', false, false, false, true, 4, true, 'This is the history of your paternal great great grandparents (via Barry Kloper, Mildred Kloper, Joe Kaplan). ', false, 'Great great great great grandparents (father''s mother''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (36, 'Myrna Vance', 'vancemyrna@yahoo.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2011-09-09 19:40:08', 597, '2010-01-31 00:00:00', '2010-08-24 00:00:00', true, false, false, false, 10, true, 'See ''Suttell/Smith side''; that Pochel family (Edward & Catherine) are your paternal great great great grandparents (via Arlie Pochel, Edward Pochel, Julius Pochel)', false, 'Great great grandparents (paternal side): <br/><a href="/families/107">Edward & Catherine Pochel</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (23, 'Evelyn Kobrin', 'EVEandRAY@aol.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-07-17 21:08:27', 342, '2005-08-29', '2010-08-26 00:00:00', false, false, false, true, 5, true, 'See ''Kobrin side''; Aaron & Rochel Kobrin are your paternal great grandparents (via Noah Kobrin and Nathan Kobrin). ', false, 'Great great great grandparents (father''s father''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (19, 'Karen Cohen', 'kj.kobrin.cohen@gmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-08-23 22:04:14', 99, '2005-08-29', '2010-08-20 00:00:00', false, false, false, true, 4, true, 'This is the history of your paternal great great grandparents (via Kal Kobrin, Joe Kaplan, and Kalman Kobrin). ', false, 'Great great great grandparents (father''s father''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (24, 'Linda Goldberg','trvrgoldberg@gmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-06-20 21:00:49', 344, '2005-08-29', '2010-09-14 00:00:00', false, false, false, true, 2, true, 'See ''Kobrin side''; Aaron & Rochel Kobrin are your paternal great grandparents (via Noah Kobrin and Nathan Kobrin).', false, 'Great great great grandparents (father''s father''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (40, 'Sandie Mechanic', 'damech@aol.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', NULL, 548, '2010-05-11 00:00:00', '2010-07-06 00:00:00', false, false, false, true, NULL, true, 'See ''Kobrin side''; Aaron & Rochel Kobrin are your maternal great great grandparents (via Evelyn Kobrin, Noah Kobrin and Nathan Kobrin).', false, 'Great great great grandparents (mother''s father''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (57, 'Martin Slon', 'martinslon@verizon.net', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-07-12 22:40:28', 715, '2010-07-07 00:00:00', '2010-09-21 00:00:00', false, false, false, true, 1, true, 'See ''Kobrin side''; Aaron & Rochel Kobrin are your paternal great grandparents (via Hymie Slon and Annie Slonimsky).', false, 'Great great grandparents (father''s mother''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (82, 'Bertha Slon', 'berthas@bigpond.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', NULL, 714, '2010-09-21 08:02:02', '2010-09-21 00:00:00', false, false, false, true, 0, true, 'See ''Kobrin side''; Aaron & Rochel Kobrin were Hymie''s maternal grandparents (via Annie Slonimsky).', false, 'Hymie Slon''s great grandparents (mother''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (21, 'Sharon Kobrin', 'sharon@kobrin.co.uk', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2011-02-11 03:10:03', 463, '2005-08-29', '2010-08-18 00:00:00', false, false, false, true, 4, true, 'See 'Kobrin side'; Aaron & Rochel Kobrin were Dave's paternal grandparents (via Joe Kobrin and Solomon Kobrin). ', false, 'Dave Kobrin''s great great grandparents (father''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (103, 'Stephanie Katz Schultz Cohen', 'redsrc@aol.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', NULL, 288, '2014-05-05 19:39:22', NULL, false, false, false, true, NULL, true, 'See ''Kobrin side''; Kal Kobrin was Arnie''s maternal great grandfather (via Dorothy Schultz and Joe Kaplan). ', false, 'Arnie Schultz''s great great great grandparents (mother''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (43, 'Pam Alman', 'pamalman@msn.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-07-07 09:58:19', 655, '2010-06-02 00:00:00', '2010-08-21 00:00:00', false, false, false, true, 2, true, 'See ''Kobrin side''; Kal Kobrin was Eric''s paternal great grandfather (via Kal Alman and Sarah Alman). ', false, 'Eric Alman''s great great great grandparents (father''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (39, 'Ann Melman', 'annmelman@gmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2008-08-18 20:33:44', 651, '2010-05-08 00:00:00', '2010-08-15 00:00:00', false, false, false, true, false, true, 'Wife of Dennis Melman, who came from Solomon Kobrin, the brother of Kal', false, 'Dennis Melman''s great great great grandparents (mother''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>, now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (56, 'Yudit Natkin', 'jnatkin@mindspring.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-07-07 21:03:29', 712, '2010-07-07 00:00:00', '2010-08-18 00:00:00', false, false, false, true, 1, true, 'See ''Kobrin side''; Aaron & Rochel Kobrin are your maternal great grandparents (via Dora Fox and Yetta Bloch)', false, 'Great great great grandparents (mother''s mother''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (76, 'Harvey Alman', 'harveyflamingo@comcast.net', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-08-20 09:36:31', 161, '2010-08-18 13:28:31', '2010-08-19 00:00:00', false, false, false, true, 1, true, 'See ''Kobrin side''; Aaron & Rochel Kobrin are your maternal great grandparents (via Sarah Alman and Kalman Kobrin). ', false, ' Great great grandparents (mother''s father''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (54, 'Jacob Alman', 'Sportsfan5390@aol.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-11-26 16:21:46', 674, '2010-07-05 00:00:00', '2010-08-18 00:00:00', false, false, false, true, 9, true, 'See ''Kobrin side''; Kalman Kaplan is your paternal great great grandpfather (via Steven Alman, Harvey Alman, Sarah Alman). ', false, 'Great great great great grandparents (father''s father''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (85, 'Caren Adams', 'CarenA4GT@aol.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2011-09-11 19:20:07', 183, '2011-07-21 15:55:42', NULL, false, true, false, false, 3, true, 'This is the history of your paternal grandparents (via James Husband, Bob''s brother)', false, ' Great great grandparents (father''s father''s side): <br/><a href=/family/family.asp?familyid=172>Thomas & Elanor Husband</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access, husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (88, 'Ashley Johnson', 'acs0918d1@yahoo.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', NULL, 229, now(), '2016-01-03 00:00:00', true, false, false, false, 0, true, 'This is the history of your mom''s mom''s side (Kay Husband was Viola''s sister)', false, '<a href="/families/218">The Zöhlers (Mathias & Maria)</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (58, 'Barry Slon', 'barry.slon@gmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', NULL, 716, '2010-07-07 00:00:00', NULL, false, false, false, true, NULL, true, 'See ''Kobrin side''; Aaron & Rochel Kobrin are your paternal great grandparents (via Hymie Slon and Annie Slonimsky).', false, 'Great great grandparents (father''s mother''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access, husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (89, 'Tony Gorruso', 'Ttrumpetguy@gmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', NULL, 71, now(), now(), true, false, false, false, NULL, true, 'This is the history of your mom''s side (Kay Husband was Viola''s sister)', false, '<a href="/families/218">The Zöhlers (Mathias & Maria)</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (59, 'Daniella Slon', 'dslon08@gmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', NULL, 717, '2010-07-07 00:00:00', NULL, false, false, false, true, NULL, true, 'See ''Kobrin side''; Aaron & Rochel Kobrin are your paternal great grandparents (via Abe Slon and Annie Slonimsky).', false, 'Great great grandparents (father''s mother''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

--and sent facebook request 1/12
INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (52, 'Brian Sneag', 'bsneag@ibi.co.za', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-07-13 08:37:04', 680, '2010-07-02 00:00:00', '2010-08-20 00:00:00', false, false, false, true, 10, true, 'See ''Kobrin side''; Aaron & Rochel Kobrin are your paternal great grandparents (via Louis Sneag and Beila Sneag).', false, 'Great great grandparents (father''s mother''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (53, 'Doreen Fittinghoff', 'mfitt@global.co.za', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-07-08 14:25:27', 682, '2010-07-02 00:00:00', '2016-01-16 00:00:00', false, false, false, true, 2, true, 'See ''Kobrin side''; Aaron & Rochel Kobrin are your paternal great grandparents (via Louis Sneag and Beila Sneag).', false, 'Great great great grandparents (father''s mother''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

- for anyone with a NULL created_at, I'll use a generic 'old site' value of '2005-08-29'
done: 42

update users set last_pestered = '2015-12-14' where id in (2, 3, 4);
update users set last_pestered = '2015-12-19' where id in (7, 6, 5);
update users set last_pestered = '2015-12-20' where id in (18, 36, 32, 9);
update users set last_pestered = '2015-12-23' where id in (49, 50, 89, 51);
update users set last_pestered = '2015-12-24' where id in (20);
update users set last_pestered = '2015-12-25' where id in (34);
update users set last_pestered = '2015-12-26' where id in (10, 12, 8, 104);
update users set last_pestered = '2015-12-29' where id in (48);
update users set last_pestered = '2015-12-30' where id in (23, 19, 24, 40);
update users set last_pestered = '2015-12-31' where id in (24);
update users set last_pestered = '2016-01-01' where id in (40, 57);
update users set last_pestered = '2016-01-02' where id in (82, 22, 4, 21, 103, 43, 39, 49, 56, 76, 54, 85);
update users set last_pestered = '2016-01-03' where id in (58);
update users set last_pestered = '2016-01-04' where id in (49, 59);
update users set last_pestered = '2016-01-08' where id in (89, 22, 48, 76, 52, 40, 49, 88);
update users set last_pestered = '2016-01-09' where id in (82, 58, 57);

===left off:


---remaining kobrins (4, emailed):

--also facebook messaged 1/12
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (68, 'gsneag@pacbell.net', false, 'garden01', '2010-07-14 12:04:17', 741, '2010-07-14 08:44:08', '2010-08-23 00:00:00', false, false, false, true, true, true, 'Gary/Maurice/Beila Kobrin', false, ' Great great grandparents (father''s mother''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (81, 'Dennis Kobrin', 'denvic35@orange.fr', false, 'DKpassword', NULL, 347, '2010-09-19 09:54:09', '2010-09-19 00:00:00', false, false, false, true, false, true, 'Nathan/Sam/Dennis', false, ' Great great great grandparents (father\'s father\'s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (84, 'Neville Kobrin', 'stanchait12@gmail.com', false, 'NKpassword', NULL, 350, '2011-05-19 07:17:29', NULL, false, false, false, true, false, true, 'Neville comes from Nathan Kobrin via Toly ', false, ' Great great grandparents (father''s father''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (87, 'allan_marcus@student.uml.edu', false, 'AMpassword', NULL, 857, '2012-01-17 21:59:40', NULL, false, false, false, true, false, true, 'Great-grandson of Sarah Alman', false, ' Great great great great great grandparents (father''s father''s side): <br/><a href="/families/194">Joseph & Sarah Kobrin</a>',  now());


---remaining kemlers & zorns (15):
INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (17, 'Danielle Shapiro', 'daniellemarisberger@gmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', NULL, 112, '2005-08-29', NULL, false, false, true, false, 0, true, 'This is the history of your maternal grandfather (Norman Kemler was Gert''s sister)', false, 'Father''s father''s side: 2 sets of great great grandparents:<br/><a href="/families/3">Ida & Barnett Kaplan</a><br/><a href="/families/4">Solomon & Ida Kemler</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (33, 'Marissa McDonald', 'marissakemler@hotmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2009-11-30 17:10:06', 120, NULL, '2010-06-19 00:00:00', false, false, true, false, true, true, 'This is the history of your paternal grandfather (Norman Kemler was Gert''s sister)', false, 'Father''s father''s side: 2 sets of great great grandparents:<br/><a href="/families/3">Ida & Barnett Kaplan</a><br/><a href="/families/4">Solomon & Ida Kemler</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (16, 'Rachel Weeks', 'rachel_weeks04@yahoo.com', false, 'berger01', '2010-03-21 20:30:00', 133, '2005-08-29', '2010-03-16 00:00:00', false, false, true, false, 3, true, '', false, NULL, now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (13, 'Joan Kemler', 'jlazkem@aol.com', false, 'password', NULL, 118, '2005-08-29', NULL, false, false, true, false, 0, true, NULL, false, NULL, now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (37, 'Deb Kallman','deborah7@charter.net', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2010-03-27 18:38:03', 125, '2010-03-21 00:00:00', '2010-05-07 00:00:00', false, false, true, false, 3, true, 'Debbie is the daughter of Eleanor & Wally', false, 'Mother''s father''s side: 2 sets of great great grandparents:<br/><a href="/families/3">Ida & Barnett Kaplan</a><br/><a href="/families/4">Solomon & Ida Kemler</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (14, Eleanor Feinberg', 'eleanorfeinberg@sbcglobal.net', false, 'password', NULL, 114,'2005-08-29', '2010-11-13 00:00:00', false, false, true, false, 0, true, NULL, false, 'Father''s side: 2 sets of great grandparents:<br/><a href="/families/3">Ida & Barnett Kaplan</a><br/><a href="/families/4">Solomon & Ida Kemler</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (86, 'kkatelan@yahoo.com', false, '$2y4fun', '2012-02-24 23:30:22', 627, '2012-01-12 18:26:54', NULL, false, false, true, false, 6, true, 'granddaughter of Stanley', false, 'Great great grandparents (father\'\'s father\'\'s side): <br/><a href=/family/family.asp?familyid=3>Ida & Solomon Kemler</a> and <a href=/family/family.asp?familyid=3>Fanny & Barnett Kobrin</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (47, 'smkelk@earthlink.net', true, 'password', NULL, 117, '2010-06-15 00:00:00', NULL, false, false, true, false, false, true, NULL, false, NULL, now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (83, 'dscohen00@gmail.com', false, 'DCpassword', '2013-12-31 06:36:28', 836, '2010-11-21 16:32:45', NULL, false, false, true, false, 4, true, 'Grandson of Rose Kemler', false, ' Great grandparents (father\'\'s mother\'\'s side): <br/><a href=/family/family.asp?familyid=4>Solomon & Ida Kemler</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (77, 'petezorn@comcast.net', false, 'password', NULL, 166, '2010-08-22 23:02:20', '2010-08-22 00:00:00', false, false, true, false, false, true, 'Child of Stu & Elaine', false, ' Great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (41, 'thezorns@gmail.com', true, 'ppj462', '2010-08-23 13:47:53', 6, '2010-05-12 00:00:00', '2010-08-21 00:00:00', false, false, true, false, 5, true, '', false, 'Great grandparents (mother\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (42, 'jbzorn1@comcast.net', false, 'JZpassword', NULL, 8, '2010-05-12 00:00:00', '2010-08-21 00:00:00', false, false, true, false, false, true, '', false, 'Great grandparents (mother\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (78, 'ZornAdams.Pamela@tatravelcenters.com', false, 'password', '2010-08-22 23:24:37', 167, '2010-08-22 23:02:58', '2010-08-22 00:00:00', false, false, true, false, true, true, 'Child of Stu & Elaine', false, ' Great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (79, 'jeremy.zorn@gmail.com', false, 'password', '2010-08-22 23:34:46', 168, '2010-08-22 23:03:16', '2010-08-22 00:00:00', false, false, true, false, true, true, 'Child of Stu & Elaine', false, ' Great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (80, 'thezorns@gmail.com', true, 'ppj462', NULL, 7, '2010-08-22 23:13:20', '2010-08-22 00:00:00', false, false, true, false, false, true, '', false, '', now());


---remaining keems (3, emailed): 

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (25, 'ansuincg@buffalostate.edu', false, 'password', NULL, 70, NULL, '2010-10-25 00:00:00', true, false, false, false, false, true, NULL, false, '<a href="/families/218">The Zöhlers (Mathias & Maria)</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (27, 'tjk@kih.net', false, 'MariA1946K', '2010-05-09 14:41:29', 69, NULL, '2010-10-25 00:00:00', true, false, false, false, 2, true, '', false, '<a href="/families/218">The Zöhlers (Mathias & Maria)</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (71, 'ansuini.c@law.wlu.edu', false, 'password', NULL, 218, '2010-07-21 00:05:00', '2010-10-25 00:00:00', true, false, false, false, false, true, 'Cathy\'s daughter', false, '5 sets of great great great great great great great great grandparents (mother\'\'s mother\'\'s side): <br/>see hot pink families <a href=/family/history.asp?displaybranch=y>here</a>', now());

facebook messaged Ashley Johnson, Anthony (jr), Cathy, and Tony Gorruso

---remaining husbands (1):
Messaged Kara Husband on myheritage.com
Can try Caren Adams that way too if she doesn't respond on email



--may skip (married in, probably don't really care):

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (15, 'wfeinber@uiuc.edu', false, 'password', NULL, 116, '2005-08-29', NULL, false, false, true, false, 0, true, NULL, false, NULL, now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (38, 'judyforeman@myhealthsense.com', false, 'password', '2010-05-07 22:03:39', 648, '2010-05-06 00:00:00', '2010-07-06 00:00:00', false, false, true, true, true, true, '', false, NULL, now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (31, 'MUnger@rubinrudman.com', false, 'password', NULL, 296, NULL, '2010-10-25 00:00:00', true, true, false, false, false, true, NULL, false, NULL, now());


won't this time: 

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (11, 'b.svikhart@comcast.net', false, 'password', NULL, 109, '2005-08-29', NULL, false, false, true, false,0, false, NULL, false, NULL, now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (30, 'eghart@msn.com', false, 'joannbarbara', '2009-11-30 22:13:38', 452, NULL, '2010-03-16 00:00:00', false, false, true, false, 2, true, '', false, NULL, now());

(email got sent back)
INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (28, 'Kevin Husband', 'khusband@realtyusa.com', false, 'password', NULL, 182, NULL, NULL, false, true, false, false, false, true, NULL, false, 'Great great grandparents (father''s father''s side): <br/><a href=\"/family/family.asp?familyid=172\">Thomas & Elanor Husband</a>', now());
