

Did these find/replace:
curly quotes with '
  'userID' INTEGER NOT NULL AUTO_INCREMENT, - id
  'sharedAccount' TINYINT(1) DEFAULT false, - shared_account
  'lastLogin' DATETIME, - last_login
  'personID' INTEGER DEFAULT false, - person_id
  'createDate' DATETIME, - created_at
  'lastPestered' DATETIME, - last_pestered
  'KeemAccess' TINYINT(1) DEFAULT false, - keem_access
  'HusbandAccess' TINYINT(1) DEFAULT false, - husband_access
  'KemlerAccess' TINYINT(1) DEFAULT false, - kemler_access
  'KaplanAccess' TINYINT(1) DEFAULT false, - kaplan_access
  'ActiveBool' TINYINT(1) DEFAULT false, - active_bool
  'connection_notes' VARCHAR(255), 
  'superAdmin' TINYINT(1) DEFAULT false,  -super_admin
  'furthestHTML' VARCHAR(255), - furthest_html
- remove quotes from table name and column names
- added onto the end:  updated_at)
- added date at the end: now());

- false,> ,false, (with leading space)
-  true, -> ,true, (with leading space)
 -> [nothing]
- replace bools with true/false
- for anyone with a NULL created_at, I'll use a generic 'old site' value of '2005-08-29'

- bcrypt the passwords

#
# Table structure for table users
#

DROP TABLE IF EXISTS users;

CREATE TABLE users (
  'userID' INTEGER NOT NULL AUTO_INCREMENT, 
  'email' VARCHAR(50), 
  'sharedAccount' TINYINT(1) DEFAULT false, 
  'password' VARCHAR(50) NOT NULL, 
  'lastLogin' DATETIME, 
  'personID' INTEGER DEFAULT false, 
  'createDate' DATETIME, 
  'lastPestered' DATETIME, 
  'KeemAccess' TINYINT(1) DEFAULT false, 
  'HusbandAccess' TINYINT(1) DEFAULT false, 
  'KemlerAccess' TINYINT(1) DEFAULT false, 
  'KaplanAccess' TINYINT(1) DEFAULT false, 
  'Logins' INTEGER DEFAULT false, 
  'ActiveBool' TINYINT(1) DEFAULT false, 
  'connection_notes' VARCHAR(255), 
  'superAdmin' TINYINT(1) DEFAULT false, 
  'furthestHTML' VARCHAR(255), 
  INDEX ('personID'), 
  PRIMARY KEY ('userID'), 
  INDEX ('userID')
) ENGINE=myisam DEFAULT CHARSET=utf8;

SET autocommit=1;

#
# Dumping data for table users
#


INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (3, 'Susan Kaplan', 'kaplanfin@aol.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2011-08-16 13:59:13', 81, '2005-08-29', '2010-10-25 00:00:00', true, true, true, true, 16, true, '', true, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>', now());

INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (1, 'Diane Kaplan', 'dianekaplan@gmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2015-01-04 18:47:15', 86, '2005-08-29', '2010-10-25 00:00:00', true, true, true, true, 417, true, '', true, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>\t ', now());
INSERT INTO users (id, name, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (2, 'Larry Kaplan', 'lkaplan000@gmail.com', false, '$2y$10$eOAL7mwV3ov9LOmMa/DgNu0iOt/IH/90fNt5Scva2taZss8PLi5AW', '2014-05-10 17:08:18', 85, '2005-08-29', '2010-10-25 00:00:00', true, true, true, true, 10, true, '', true, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>', now());



INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (6, 'rhusband@saintclares.org', false, 'bobhpsw1', '2014-05-08 14:43:43', 80, '2005-08-29','2010-10-25 00:00:00', true, true, false, false, 13, true, '', false, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (7, 'ekdolph@comcast.net', false, 'password', '2010-07-08 22:35:06', 37, '2005-08-29', '2010-11-13 00:00:00', false, false, true, true, 2, true, '', false, '<a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a>,<a href=\"/family/family.asp?familyid=4\">Sol & Ida Kemler</a>,<a href=\"/family/family.asp?familyid=90\">Aaron & Rochel Kobrin</a>,<a href=\"/family/family.asp?familyid=119\">Max & Toba Shapiro</', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (8, 'bartlett.d@husky.neu.edu', false, 'password', '2010-10-26 09:17:07', 83, '2005-08-29', '2010-10-25 00:00:00', true, true, false, false, 1, true, '', false, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (9, 'ladolph@comcast.net', false, 'password', NULL, 40, '2005-08-29', NULL, false, false, true, true, 0, true, NULL, false, '<a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a>,<a href=\"/family/family.asp?familyid=4\">Sol & Ida Kemler</a>,<a href=\"/family/family.asp?familyid=90\">Aaron & Rochel Kobrin</a>,<a href=\"/family/family.asp?familyid=119\">Max & Toba Shapiro</', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (10, 'aok@aya.yale.edu', false, 'password', '2010-06-27 18:10:21', 108, '2005-08-29', '2010-06-27 00:00:00', false, false, true, false, 1, true, '', false, 'Fathers side: 2 sets of great grandparents:<br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (11, 'b.svikhart@comcast.net', false, 'password', NULL, 109, '2005-08-29', NULL, false, false, true, false,0, false, NULL, false, NULL, now());


INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (12, 'bethkemler@aol.com', false, 'password', '2010-07-13 21:52:22', 106, '2005-08-29', '2010-11-13 00:00:00', false, false, true, false, 2, true, '', false, 'Fathers side: 2 sets of great grandparents:<br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (13, 'jlazkem@aol.com', false, 'password', NULL, 118, '2005-08-29', NULL, false, false, true, false, 0, true, NULL, false, NULL, now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (14, 'eleanorfeinberg@sbcglobal.net', false, 'password', NULL, 114,'2005-08-29', '2010-11-13 00:00:00', false, false, true, false, 0, true, NULL, false, 'Fathers side: 2 sets of great grandparents:<br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (15, 'wfeinber@uiuc.edu', false, 'password', NULL, 116, '2005-08-29', NULL, false, false, true, false, 0, true, NULL, false, NULL, now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (16, 'rachel_weeks04@yahoo.com', false, 'berger01', '2010-03-21 20:30:00', 133, '2005-08-29', '2010-03-16 00:00:00', false, false, true, false, 3, true, '', false, NULL, now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (17, 'dberger@wellesley.edu', false, 'password', NULL, 112, '2005-08-29', NULL, false, false, true, false, 0, true, NULL, false, 'Fathers fathers side: 2 sets of great great grandparents:<br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>', now());



INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (4, 'kenkaplan@aol.com', false, 'password', '2013-08-30 21:56:03', 36, '2005-08-29', '2010-11-13 00:00:00', true, true, true, true, 14, true, NULL, false, '<a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a>,<a href=\"/family/family.asp?familyid=4\">Sol & Ida Kemler</a>,<a href=\"/family/family.asp?familyid=90\">Aaron & Rochel Kobrin</a>,<a href=\"/family/family.asp?familyid=119\">Max & Toba Shapiro</', now());

<!--left off here-->
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (19, 'kj.kobrin.cohen@gmail.com', false, 'sunspot', '2010-08-23 22:04:14', 99, '2005-08-29', '2010-08-20 00:00:00', false, false, false, true, 4, true, 'Kal was cousins with dad (his dad was Joe), Karen is his daughter and second cousins with me', false, 'Great great great grandparents (fathers fathers side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (20, 'joseph@kobrin.co.uk', false, 'password', NULL, 464, NULL, '2010-07-06 00:00:00', false, false, false, true, false, true, NULL, false, 'Great great great grandparents (father\'s father\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (21, 'sharon@kobrin.co.uk', false, 'norahs', '2011-02-11 03:10:03', 463, NULL, '2010-08-18 00:00:00', false, false, false, true, 4, true, 'Sharon married Dave Kobrin.  Dave and dad are second cousins: Dave came from Solomon via Joe, and dad came from his brother Kalman via Larry. ', false, NULL, now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (22, 'PRECHER@aol.com', false, 'Natick68', '2014-02-09 18:14:57', 188, NULL, '2010-08-21 00:00:00', false, false, false, true, 5, true, 'Barry Kloper my second cousin: the son of Mildred, the daughter of Joe Kaplan, who was the brother of Abraham ', false, 'Great great great grandparents (mother\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (23, 'EVEandRAY@aol.com', false, 'password', '2010-07-17 21:08:27', 342, NULL, '2010-08-26 00:00:00', false, false, false, true, 5, true, 'Evelyn and dad are second cousins: Evelyn came from Nathan via Noah, and dad came from his brother Kalman via Larry. ', false, 'Great great great grandparents (father\'s father\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (24, 'tgoldberg@carolina.rr.com', true, 'cessnagold', '2010-06-20 21:00:49', 344, NULL, '2010-09-14 00:00:00', false, false, false, true, 2, true, 'Linda and dad are second cousins: Linda came from Nathan via Noah, and dad came from his brother Kalman via Larry.', false, 'Great great great grandparents (father\'s father\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (25, 'ansuincg@buffalostate.edu', false, 'password', NULL, 70, NULL, '2010-10-25 00:00:00', true, false, false, false, false, true, NULL, false, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (26, 'scudieroan@Dare.k12.nc.us', false, 'password', NULL, 72, NULL, '2010-10-25 00:00:00', true, false, false, false, false, true, NULL, false, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (27, 'tjk@kih.net', false, 'MariA1946K', '2010-05-09 14:41:29', 69, NULL, '2010-10-25 00:00:00', true, false, false, false, 2, true, '', false, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (28, 'khusband@realtyusa.com', false, 'password', NULL, 182, NULL, NULL, false, true, false, false, false, true, NULL, false, 'Great great grandparents (father\'s father\'s side): <br/><a href=\"/family/family.asp?familyid=172\">Thomas & Elanor Husband</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (30, 'eghart@msn.com', false, 'joannbarbara', '2009-11-30 22:13:38', 452, NULL, '2010-03-16 00:00:00', false, false, true, false, 2, true, '', false, NULL, now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (31, 'MUnger@rubinrudman.com', false, 'password', NULL, 296, NULL, '2010-10-25 00:00:00', true, true, false, false, false, true, NULL, false, NULL, now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (32, 'acdolph@comcast.net', false, 'password', NULL, 39, NULL, NULL, false, false, true, true, false, true, NULL, false, '<a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a>,<a href=\"/family/family.asp?familyid=4\">Sol & Ida Kemler</a>,<a href=\"/family/family.asp?familyid=90\">Aaron & Rochel Kobrin</a>,<a href=\"/family/family.asp?familyid=119\">Max & Toba Shapiro</', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (33, 'marissakemler@hotmail.com', false, 'password', '2009-11-30 17:10:06', 120, NULL, '2010-06-19 00:00:00', false, false, true, false, true, true, '', false, 'Father\'s father\'s side: 2 sets of great great grandparents:<br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (34, 'rschultz44@aol.com', false, 'password', '2010-02-04 13:27:00', 96, '2010-01-24 00:00:00', '2010-08-20 00:00:00', false, false, false, true, 2, true, 'Rosealyn is my second cousin once removed, coming from Jeff Schultz (my second cousin), Dorothy Schultz (cousins with dad), and Joe Kaplan. ', false, 'Great great great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (35, 'dianekaplan@gmail.com', true, 'password1', '2011-02-11 03:06:21', 24, '2010-01-24 00:00:00', NULL, false, false, true, false, 33, true, NULL, false, NULL, now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (36, 'vancemyrna@yahoo.com', false, 'bernie2', '2011-09-09 19:40:08', 597, '2010-01-31 00:00:00', '2010-08-24 00:00:00', true, false, false, false, 10, true, 'Myrna would have been third cousins with grandma: she came from Arlie, Edward, and Julius Pochel, and Julius was the sister of Emily, who had Helen/Adele/grandma', false, 'Great great grandparents (father\'s father\'s side): <br/><a href=\"/family/family.asp?familyid=107\">Edward & Catherine Pochel</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (37, 'deborah7@charter.net', false, 'password', '2010-03-27 18:38:03', 125, '2010-03-21 00:00:00', '2010-05-07 00:00:00', false, false, true, false, 3, true, 'Debbie is the daughter of Eleanor & Wally', false, 'Mother\'s father\'s side: 2 sets of great great grandparents:<br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (86, 'kkatelan@yahoo.com', false, '$2y4fun', '2012-02-24 23:30:22', 627, '2012-01-12 18:26:54', NULL, false, false, true, false, 6, true, 'granddaughter of Stanley', false, 'Great great grandparents (father\'\'s father\'\'s side): <br/><a href=/family/family.asp?familyid=3>Ida & Solomon Kemler</a> and <a href=/family/family.asp?familyid=3>Fanny & Barnett Kobrin</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (5, 'bartlett.family@comcast.net', false, 'password', '2010-07-05 20:05:51', 79, NULL, '2010-10-25 00:00:00', true, true, false, false, 5, true, '', false, '<a href=\"/family/family.asp?familyid=218\">The Zöhlers (Mathias & Maria)</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (38, 'judyforeman@myhealthsense.com', false, 'password', '2010-05-07 22:03:39', 648, '2010-05-06 00:00:00', '2010-07-06 00:00:00', false, false, true, true, true, true, '', false, NULL, now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (39, 'annmelman@gmail.com', false, 'password', '2008-08-18 20:33:44', 651, '2010-05-08 00:00:00', '2010-08-15 00:00:00', false, false, false, true, false, true, 'Wife of Dennis Melman, who came from Solomon Kobrin, the brother of Kal', false, NULL, now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (40, 'damech@aol.com', false, 'password', NULL, 548, '2010-05-11 00:00:00', '2010-07-06 00:00:00', false, false, false, true, false, true, 'Daughter of Evelyn: her great-grandfather (Nathan Kobrin) was brothers with mine, Kalman Kaplan ', false, 'Great great great grandparents (mother\'s father\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (41, 'thezorns@gmail.com', true, 'ppj462', '2010-08-23 13:47:53', 6, '2010-05-12 00:00:00', '2010-08-21 00:00:00', false, false, true, false, 5, true, '', false, 'Great grandparents (mother\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (42, 'jbzorn1@comcast.net', false, 'JZpassword', NULL, 8, '2010-05-12 00:00:00', '2010-08-21 00:00:00', false, false, true, false, false, true, '', false, 'Great grandparents (mother\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (43, 'pamalman@msn.com', false, 'saltsk8', '2010-07-07 09:58:19', 655, '2010-06-02 00:00:00', '2010-08-21 00:00:00', false, false, false, true, 2, true, 'widow of Eric Alman, who was the grandson of Sarah Alman. Sarah was the sister of Larry/Abraham', false, NULL, now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (45, 'dianekaplan@gmail.com', true, 'password1', '2010-06-15 23:50:22', 105, '2010-06-12 00:00:00', NULL, false, false, true, false, 2, true, NULL, false, NULL, now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (46, 'tgoldberg@carolina.rr.com', true, 'cessnagold', NULL, 498, '2010-06-15 00:00:00', '2010-07-06 00:00:00', false, false, false, true, false, true, 'Linda and dad are second cousins: Linda came from Nathan via Noah, and dad came from his brother Kalman via Larry.', false, NULL, now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (47, 'smkelk@earthlink.net', true, 'password', NULL, 117, '2010-06-15 00:00:00', NULL, false, false, true, false, false, true, NULL, false, NULL, now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (48, 'Kittyfelone@Gmail.com', false, 'dragon', '2011-01-01 20:32:04', 573, '2010-06-19 00:00:00', '2010-08-21 00:00:00', false, false, false, true, 4, true, 'daughter of Barry Kloper, son of Mildred, cousin of dad', false, 'Great great great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (49, 'JudiKO@AOL.COM', false, 'JKpassword', NULL, 189, '2010-06-19 00:00:00', '2010-08-21 00:00:00', false, false, false, true, false, true, 'Mildred was the cousin of dad, and Judi is her daughter (sister of Barry Kloper)', false, 'Great great great grandparents (mother\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (50, 'hon600rr@yahoo.com', false, 'password', '2010-06-20 16:31:38', 572, '2010-06-20 00:00:00', '2010-08-21 00:00:00', false, false, false, true, true, true, 'Wendy is the daughter of Barry Kloper', false, 'Great great great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (51, 'andreaobrien1@hotmail.com', false, 'password', '2011-03-23 20:30:20', 89, '2010-06-23 00:00:00', '2010-07-06 00:00:00', false, false, false, true, 8, true, 'Andrea is the daughter of Kal, cousin of dad', false, 'Great great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (54, 'Sportsfan5390@aol.com', false, 'bruschi', '2010-11-26 16:21:46', 674, '2010-07-05 00:00:00', '2010-08-18 00:00:00', false, false, false, true, 9, true, 'Jacob came from Sarah Alman, Harvey, Steven', false, 'Great great great great grandparents (father\'s father\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (56, 'jnatkin@mindspring.com', false, 'password', '2010-07-07 21:03:29', 712, '2010-07-07 00:00:00', '2010-08-18 00:00:00', false, false, false, true, true, true, 'Aaron/Yetta/Dora', false, 'Great great great grandparents (mother\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (71, 'ansuini.c@law.wlu.edu', false, 'password', NULL, 218, '2010-07-21 00:05:00', '2010-10-25 00:00:00', true, false, false, false, false, true, 'Cathy\'s daughter', false, '5 sets of great great great great great great great great grandparents (mother\'\'s mother\'\'s side): <br/>see hot pink families <a href=/family/history.asp?displaybranch=y>here</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (76, 'harveyflamingo@att.net', false, 'tennis11', '2010-08-20 09:36:31', 161, '2010-08-18 13:28:31', '2010-08-19 00:00:00', false, false, false, true, true, true, 'Son of Sarah Kaplan', false, ' Great great grandparents (mother\'s father\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (77, 'petezorn@comcast.net', false, 'password', NULL, 166, '2010-08-22 23:02:20', '2010-08-22 00:00:00', false, false, true, false, false, true, 'Child of Stu & Elaine', false, ' Great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (52, 'bsneag@ibi.co.za', false, 'password', '2010-07-13 08:37:04', 680, '2010-07-02 00:00:00', '2010-08-20 00:00:00', false, false, false, true, 10, true, 'Brian is dad\'s second cousin, he came down through Beila', false, 'Great great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (53, 'mfitt@global.co.za', false, 'password', '2010-07-08 14:25:27', 682, '2010-07-02 00:00:00', '2010-08-20 00:00:00', false, false, false, true, 2, true, 'Doreen is dad\'s second cousin, he came down through Beila', false, 'Great great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (57, 'martinslon@verizon.net', false, 'password', '2010-07-12 22:40:28', 715, '2010-07-07 00:00:00', '2010-09-21 00:00:00', false, false, false, true, true, true, 'Aaron/Annie/Hymie/Martin', false, 'Great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (58, 'barry.slon@gmail.com', false, 'password', NULL, 716, '2010-07-07 00:00:00', NULL, false, false, false, true, false, true, 'Aaron/Annie/Hymie/Barry', false, 'Great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (59, 'editordan2002@yahoo.com', false, 'password', NULL, 717, '2010-07-07 00:00:00', NULL, false, false, false, true, false, true, 'Aaron/Annie/Abe/Daniella', false, 'Great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (78, 'ZornAdams.Pamela@tatravelcenters.com', false, 'password', '2010-08-22 23:24:37', 167, '2010-08-22 23:02:58', '2010-08-22 00:00:00', false, false, true, false, true, true, 'Child of Stu & Elaine', false, ' Great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (79, 'jeremy.zorn@gmail.com', false, 'password', '2010-08-22 23:34:46', 168, '2010-08-22 23:03:16', '2010-08-22 00:00:00', false, false, true, false, true, true, 'Child of Stu & Elaine', false, ' Great great grandparents (father\'s mother\'s side): <br/><a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/><a href=\"/family/family.asp?familyid=4\">Solomon & Ida Kemler</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (80, 'thezorns@gmail.com', true, 'ppj462', NULL, 7, '2010-08-22 23:13:20', '2010-08-22 00:00:00', false, false, true, false, false, true, '', false, '', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (68, 'gsneag@pacbell.net', false, 'garden01', '2010-07-14 12:04:17', 741, '2010-07-14 08:44:08', '2010-08-23 00:00:00', false, false, false, true, true, true, 'Gary/Maurice/Beila Kobrin', false, ' Great great grandparents (father\'\'s mother\'\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (81, 'denvic35@orange.fr', false, 'DKpassword', NULL, 347, '2010-09-19 09:54:09', '2010-09-19 00:00:00', false, false, false, true, false, true, 'Nathan/Sam/Dennis', false, ' Great great great grandparents (father\'s father\'s side): <br/><a href=\"/family/family.asp?familyid=194\">Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (82, 'berthas@bigpond.com', false, 'BSpassword', NULL, 714, '2010-09-21 08:02:02', '2010-09-21 00:00:00', false, false, false, true, false, true, 'Bertha married Hymie, son of Kalman\'\'s sister Annie', false, '', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (83, 'dscohen00@gmail.com', false, 'DCpassword', '2013-12-31 06:36:28', 836, '2010-11-21 16:32:45', NULL, false, false, true, false, 4, true, 'Grandson of Rose Kemler', false, ' Great grandparents (father\'\'s mother\'\'s side): <br/><a href=/family/family.asp?familyid=4>Solomon & Ida Kemler</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (84, 'stanchait12@gmail.com', false, 'NKpassword', NULL, 350, '2011-05-19 07:17:29', NULL, false, false, false, true, false, true, 'Neville comes from Nathan Kobrin via Toly ', false, ' Great great grandparents (father\'\'s father\'\'s side): <br/><a href=/family/family.asp?familyid=194>Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (85, 'CarenA4GT@aol.com', false, 'CApassword', '2011-09-11 19:20:07', 183, '2011-07-21 15:55:42', NULL, false, true, false, false, 3, true, 'mom\'s cousin', false, ' Great great grandparents (father\'s father\'s side): <br/><a href=/family/family.asp?familyid=172>Thomas & Elanor Husband</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (87, 'allan_marcus@student.uml.edu', false, 'AMpassword', NULL, 857, '2012-01-17 21:59:40', NULL, false, false, false, true, false, true, 'Great-grandson of Sarah Alman', false, ' Great great great great great grandparents (father\'\'s father\'\'s side): <br/><a href=/family/family.asp?familyid=194>Joseph & Sarah Kobrin</a>', now());
INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (103, 'redsrc@aol.com', false, 'SSpassword', NULL, 288, '2014-05-05 19:39:22', NULL, false, false, false, true, false, true, 'Stephanie was the wife of Arnie, whose mother Dorothy was the first cousin of Abraham Larry Kaplan', false, 'Married into the family- spouse was: <br/><a href=/family/person.asp?personID=196>Arnie Schultz</a>', now());

INSERT INTO users (id, email, shared_account, password, last_login, person_id, created_at, last_pestered, keem_access,husband_access, kemler_access, kaplan_access, logins, active_bool, connection_notes, super_admin, furthest_html, updated_at) VALUES (18, 'dbnitkin66@hotmail.com', false, 'password', '2010-03-20 08:52:44', 420, '2005-08-29', '2010-09-14 00:00:00', false, false, true, false, 1, true, 'David and dad are second cousins: David came from Etta Nitkin via Sonny. ', false, 'Fathers Mothers side: great grandparents <a href=\"/family/family.asp?familyid=3\">Ida & Barnett Kaplan</a><br/>Fathers fathers side: great grandparents <a href=\"/family/family.asp?familyid=123\">Nathaniel & Lena Nitkin</a>', now());

# 71 records

